### ISSUE TITLE
Yet Another Wii Room Channel issue

### ISSUE THREAD

**Issue by kmannumber1** [WiiLink24/service-issues#17] opened 2021-08-03 17:00 UTC
1. What service did you run into this issue with?
Wii Room

2. What error did you encounter?
Crash (horn sound plays VERY quietly sometimes)

3. How can we reproduce this issue?
• Load (from SDHC Card)
• Click on "Theater"
• Click on "Search"
• Click the first movie
• Click "Trailer"
• Rewind
• It should close
• Reenter and rewind
From my YT channel:

https://user-images.githubusercontent.com/82726781/128056089-829d3267-3677-4c47-b6c4-1541159bfee2.mp4

**Comment by noahpistilli** [comment] 2021-08-03 18:08
This issue is caused by the fact that the GrubHub video is still encoded using Vorbis audio opposed to FastAudio/ADPCM/PCM. I will fix this right now. Closing

**Closed as completed by noahpistilli** 2021-08-03 18:08 UTC
Labels: channel-issue

**Comment by kmannumber1** [comment] 2021-08-03 21:00
It still happens, and even worse. Now it more often plays the SoD.
